// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {auth} from '../models';
import {fleet} from '../models';
import {configmgr} from '../models';
import {audit} from '../models';
import {main} from '../models';
import {lease} from '../models';
import {tunnel} from '../models';
import {json} from '../models';
import {fs} from '../models';
import {traffic} from '../models';
import {easytier} from '../models';

export function Accounts():Promise<Array<auth.Account>>;

export function AgentCommand(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<fleet.Command>;

export function AgentCommands():Promise<Array<fleet.Command>>;

export function AppInfo():Promise<Record<string, string>>;

export function ApplyConfigs(arg1:Array<configmgr.ConfigFile>,arg2:Array<string>):Promise<void>;

export function AuditLog(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AuditTail(arg1:number):Promise<Array<audit.Entry>>;

export function Authenticate(arg1:string,arg2:string):Promise<auth.Account|boolean>;

export function CheckSubnetConflict(arg1:string):Promise<boolean>;

export function ClearFleetPin():Promise<void>;

export function ClearTunnelHistory():Promise<number>;

export function CloudflaredStatus():Promise<Record<string, string>>;

export function CoreLog():Promise<Array<string>>;

export function CoreStatus():Promise<string>;

export function CreateAgent(arg1:string):Promise<main.AgentEnrollment>;

export function DeleteAccount(arg1:string):Promise<void>;

export function DeleteAgent(arg1:string):Promise<void>;

export function DeleteConfig(arg1:string):Promise<void>;

export function DeleteUser(arg1:string):Promise<void>;

export function ForgetLease(arg1:string):Promise<void>;

export function GetConfig(arg1:string):Promise<configmgr.ConfigFile>;

export function GetSettings():Promise<string>;

export function HasWebAccount():Promise<boolean>;

export function Init():Promise<void>;

export function InstallCloudflared():Promise<void>;

export function IsAdmin():Promise<boolean>;

export function LaunchService(arg1:string,arg2:number,arg3:string):Promise<void>;

export function ListAgents():Promise<Array<fleet.Agent>>;

export function ListConfigs():Promise<Array<configmgr.ConfigFile>>;

export function ListLeases():Promise<Record<string, lease.Lease>>;

export function ListSessions():Promise<Array<Record<string, any>>>;

export function ListTunnels():Promise<Array<tunnel.Tunnel>>;

export function ListUsers():Promise<Array<Record<string, any>>>;

export function LocalSubnets():Promise<Array<string>>;

export function Metrics(arg1:number):Promise<string>;

export function NodeInfo():Promise<json.RawMessage>;

export function OpenDir(arg1:string):Promise<void>;

export function Peers():Promise<json.RawMessage>;

export function PingDiagnostic(arg1:string,arg2:number):Promise<main.PingResult>;

export function ProbeMTU(arg1:string):Promise<number>;

export function RelaunchAsAdmin():Promise<void>;

export function RestartCore():Promise<void>;

export function RetargetTunnel(arg1:string,arg2:string):Promise<tunnel.Tunnel>;

export function RevokeOtherSessions():Promise<number>;

export function RevokeSession(arg1:string):Promise<void>;

export function RotateWebTLSCert():Promise<void>;

export function RotateWebToken():Promise<string>;

export function Routes():Promise<json.RawMessage>;

export function SSHStatus():Promise<Record<string, string>>;

export function SaveAccount(arg1:auth.Account,arg2:string):Promise<void>;

export function SaveConfig(arg1:configmgr.ConfigFile):Promise<void>;

export function SaveSettings(arg1:string):Promise<void>;

export function SaveUser(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<void>;

export function SendTestNotify():Promise<void>;

export function SetAccountPassword(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetConfigEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SetEventSink(arg1:any):Promise<void>;

export function SetNetworkRunning(arg1:string,arg2:boolean):Promise<void>;

export function SetWebAccount(arg1:string,arg2:string):Promise<void>;

export function SetWebAccountPassword(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetWebAssets(arg1:fs.FS):Promise<void>;

export function SetWebToken(arg1:string):Promise<void>;

export function StartCore():Promise<void>;

export function StartSSHTunnel(arg1:string):Promise<tunnel.Tunnel>;

export function StartTray():Promise<void>;

export function StartTunnel(arg1:string):Promise<tunnel.Tunnel>;

export function Stats():Promise<json.RawMessage>;

export function StopCore():Promise<void>;

export function StopTunnel(arg1:string):Promise<void>;

export function TrafficHistory(arg1:number):Promise<traffic.History>;

export function TunnelPeers():Promise<Array<tunnel.Peer>>;

export function Versions():Promise<easytier.Version>;

export function VpnPortal():Promise<json.RawMessage>;

export function WebAccount():Promise<string|string>;

export function WebInfo():Promise<Record<string, string>>;

export function WebTLSStatus():Promise<Record<string, string>>;

export function WebdavPull():Promise<string>;

export function WebdavPush():Promise<string>;

export function CoreReleases():Promise<Record<string, any>>;

export function CoreInstalled():Promise<Array<any>>;

export function CoreInstall(arg1:string):Promise<void>;

export function CoreSetActive(arg1:string):Promise<void>;

export function CoreDelete(arg1:string):Promise<void>;

export function DevicesList():Promise<Array<any>>;

export function DeviceApprove(arg1:string, arg2:number):Promise<void>;

export function DeviceDenyCurrent(arg1:string, arg2:string, arg3:string, arg4:string):Promise<void>;

export function DeviceRemove(arg1:string):Promise<void>;

export function AppLogTail(arg1:number):Promise<Array<string>>;
