// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Accounts() {
  return window['go']['main']['App']['Accounts']();
}

export function AgentCommand(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AgentCommand'](arg1, arg2, arg3, arg4, arg5);
}

export function AgentCommands() {
  return window['go']['main']['App']['AgentCommands']();
}

export function AppInfo() {
  return window['go']['main']['App']['AppInfo']();
}

export function ApplyConfigs(arg1, arg2) {
  return window['go']['main']['App']['ApplyConfigs'](arg1, arg2);
}

export function AuditLog(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AuditLog'](arg1, arg2, arg3, arg4);
}

export function AuditTail(arg1) {
  return window['go']['main']['App']['AuditTail'](arg1);
}

export function Authenticate(arg1, arg2) {
  return window['go']['main']['App']['Authenticate'](arg1, arg2);
}

export function CheckSubnetConflict(arg1) {
  return window['go']['main']['App']['CheckSubnetConflict'](arg1);
}

export function ClearFleetPin() {
  return window['go']['main']['App']['ClearFleetPin']();
}

export function ClearTunnelHistory() {
  return window['go']['main']['App']['ClearTunnelHistory']();
}

export function CloudflaredStatus() {
  return window['go']['main']['App']['CloudflaredStatus']();
}

export function CoreLog() {
  return window['go']['main']['App']['CoreLog']();
}

export function CoreStatus() {
  return window['go']['main']['App']['CoreStatus']();
}

export function CreateAgent(arg1) {
  return window['go']['main']['App']['CreateAgent'](arg1);
}

export function DeleteAccount(arg1) {
  return window['go']['main']['App']['DeleteAccount'](arg1);
}

export function DeleteAgent(arg1) {
  return window['go']['main']['App']['DeleteAgent'](arg1);
}

export function DeleteConfig(arg1) {
  return window['go']['main']['App']['DeleteConfig'](arg1);
}

export function DeleteUser(arg1) {
  return window['go']['main']['App']['DeleteUser'](arg1);
}

export function ForgetLease(arg1) {
  return window['go']['main']['App']['ForgetLease'](arg1);
}

export function GetConfig(arg1) {
  return window['go']['main']['App']['GetConfig'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function HasWebAccount() {
  return window['go']['main']['App']['HasWebAccount']();
}

export function Init() {
  return window['go']['main']['App']['Init']();
}

export function InstallCloudflared() {
  return window['go']['main']['App']['InstallCloudflared']();
}

export function IsAdmin() {
  return window['go']['main']['App']['IsAdmin']();
}

export function LaunchService(arg1, arg2, arg3) {
  return window['go']['main']['App']['LaunchService'](arg1, arg2, arg3);
}

export function ListAgents() {
  return window['go']['main']['App']['ListAgents']();
}

export function ListConfigs() {
  return window['go']['main']['App']['ListConfigs']();
}

export function ListLeases() {
  return window['go']['main']['App']['ListLeases']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function ListTunnels() {
  return window['go']['main']['App']['ListTunnels']();
}

export function ListUsers() {
  return window['go']['main']['App']['ListUsers']();
}

export function LocalSubnets() {
  return window['go']['main']['App']['LocalSubnets']();
}

export function Metrics(arg1) {
  return window['go']['main']['App']['Metrics'](arg1);
}

export function NodeInfo() {
  return window['go']['main']['App']['NodeInfo']();
}

export function OpenDir(arg1) {
  return window['go']['main']['App']['OpenDir'](arg1);
}

export function Peers() {
  return window['go']['main']['App']['Peers']();
}

export function PingDiagnostic(arg1, arg2) {
  return window['go']['main']['App']['PingDiagnostic'](arg1, arg2);
}

export function ProbeMTU(arg1) {
  return window['go']['main']['App']['ProbeMTU'](arg1);
}

export function RelaunchAsAdmin() {
  return window['go']['main']['App']['RelaunchAsAdmin']();
}

export function RestartCore() {
  return window['go']['main']['App']['RestartCore']();
}

export function RetargetTunnel(arg1, arg2) {
  return window['go']['main']['App']['RetargetTunnel'](arg1, arg2);
}

export function RevokeOtherSessions() {
  return window['go']['main']['App']['RevokeOtherSessions']();
}

export function RevokeSession(arg1) {
  return window['go']['main']['App']['RevokeSession'](arg1);
}

export function RotateWebTLSCert() {
  return window['go']['main']['App']['RotateWebTLSCert']();
}

export function RotateWebToken() {
  return window['go']['main']['App']['RotateWebToken']();
}

export function Routes() {
  return window['go']['main']['App']['Routes']();
}

export function SSHStatus() {
  return window['go']['main']['App']['SSHStatus']();
}

export function SaveAccount(arg1, arg2) {
  return window['go']['main']['App']['SaveAccount'](arg1, arg2);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveUser(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveUser'](arg1, arg2, arg3, arg4);
}

export function SendTestNotify() {
  return window['go']['main']['App']['SendTestNotify']();
}

export function SetAccountPassword(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetAccountPassword'](arg1, arg2, arg3);
}

export function SetConfigEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetConfigEnabled'](arg1, arg2);
}

export function SetEventSink(arg1) {
  return window['go']['main']['App']['SetEventSink'](arg1);
}

export function SetNetworkRunning(arg1, arg2) {
  return window['go']['main']['App']['SetNetworkRunning'](arg1, arg2);
}

export function SetWebAccount(arg1, arg2) {
  return window['go']['main']['App']['SetWebAccount'](arg1, arg2);
}

export function SetWebAccountPassword(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetWebAccountPassword'](arg1, arg2, arg3);
}

export function SetWebAssets(arg1) {
  return window['go']['main']['App']['SetWebAssets'](arg1);
}

export function SetWebToken(arg1) {
  return window['go']['main']['App']['SetWebToken'](arg1);
}

export function StartCore() {
  return window['go']['main']['App']['StartCore']();
}

export function StartSSHTunnel(arg1) {
  return window['go']['main']['App']['StartSSHTunnel'](arg1);
}

export function StartTray() {
  return window['go']['main']['App']['StartTray']();
}

export function StartTunnel(arg1) {
  return window['go']['main']['App']['StartTunnel'](arg1);
}

export function Stats() {
  return window['go']['main']['App']['Stats']();
}

export function StopCore() {
  return window['go']['main']['App']['StopCore']();
}

export function StopTunnel(arg1) {
  return window['go']['main']['App']['StopTunnel'](arg1);
}

export function TrafficHistory(arg1) {
  return window['go']['main']['App']['TrafficHistory'](arg1);
}

export function TunnelPeers() {
  return window['go']['main']['App']['TunnelPeers']();
}

export function Versions() {
  return window['go']['main']['App']['Versions']();
}

export function VpnPortal() {
  return window['go']['main']['App']['VpnPortal']();
}

export function WebAccount() {
  return window['go']['main']['App']['WebAccount']();
}

export function WebInfo() {
  return window['go']['main']['App']['WebInfo']();
}

export function WebTLSStatus() {
  return window['go']['main']['App']['WebTLSStatus']();
}

export function WebdavPull() {
  return window['go']['main']['App']['WebdavPull']();
}

export function WebdavPush() {
  return window['go']['main']['App']['WebdavPush']();
}

export function CoreReleases() {
  return window['go']['main']['App']['CoreReleases']();
}

export function CoreInstalled() {
  return window['go']['main']['App']['CoreInstalled']();
}

export function CoreInstall(arg1) {
  return window['go']['main']['App']['CoreInstall'](arg1);
}

export function CoreSetActive(arg1) {
  return window['go']['main']['App']['CoreSetActive'](arg1);
}

export function CoreDelete(arg1) {
  return window['go']['main']['App']['CoreDelete'](arg1);
}

export function DevicesList() {
  return window['go']['main']['App']['DevicesList']();
}

export function DeviceApprove(arg1, arg2) {
  return window['go']['main']['App']['DeviceApprove'](arg1, arg2);
}

export function DeviceDenyCurrent(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DeviceDenyCurrent'](arg1, arg2, arg3, arg4);
}

export function DeviceRemove(arg1) {
  return window['go']['main']['App']['DeviceRemove'](arg1);
}

export function AppLogTail(arg1) {
  return window['go']['main']['App']['AppLogTail'](arg1);
}
