package configmgr

import (
	"path/filepath"
	"strings"
	"sync"
	"testing"
	"time"

	"easytier-pro-gui/internal/core"
)

// TestCoreLoadsAdvancedConfig verifies a full-featured config generated by the
// UI (all advanced flags, proxy, socks5, vpn portal) is accepted by the real
// easytier-core without parse errors.
func TestCoreLoadsAdvancedConfig(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping integration test in short mode")
	}

	rpcAddr, restorePort, err := core.WithTestPort()
	if err != nil {
		t.Fatal(err)
	}
	defer restorePort()

	tmp := t.TempDir()
	old := core.DefaultPaths
	core.DefaultPaths = &core.Paths{}
	core.DefaultPaths.SetOverride(
		filepath.Join("D:\\easytierpro\\easytier-pro-gui\\resources", "bin"),
		filepath.Join("D:\\easytierpro\\easytier-pro-gui\\resources", "drivers"),
		tmp,
		filepath.Join(tmp, "configs"),
		filepath.Join(tmp, "logs"),
	)
	defer func() { core.DefaultPaths = old }()

	raw := `instance_id = "77777777-8888-8888-8888-999999999999"
instance_name = "adv-node"
dhcp = false
ipv4 = "10.50.50.1/24"
listeners = ["tcp://0.0.0.0:11010", "udp://0.0.0.0:11010"]
peers = ["wss://ez.cloud.c01.kr"]
socks5_proxy = "socks5://0.0.0.0:1080"

[[proxy_network]]
cidr = "10.100.1.0/24"

[network_identity]
network_name = "adv-net"
network_secret = "secret"

[vpn_portal_config]
wireguard_listen = "0.0.0.0:11015"
client_cidr = "10.14.14.0/24"

[[vpn_portal_config.clients]]
name = "phone"
virtual_ip = "10.144.144.3"

[flags]
dev_name = "et_adv"
mtu = 1380
latency_first = true
use_smoltcp = true
enable_ipv6 = false
enable_kcp_proxy = true
disable_quic_input = true
bind_device = true
multi_thread = true
enable_encryption = false
disable_tcp_hole_punching = true
accept_dns = true
relay_network_whitelist = "adv-net"
instance_recv_bps_limit = 1000000
no_tun = true
`

	m := NewManager(core.DefaultPaths.ConfigDir())
	if err := m.Save(ConfigFile{Enabled: true, Raw: raw}); err != nil {
		t.Fatalf("save config: %v", err)
	}

	var mu sync.Mutex
	logs := []string{}
	p := core.NewProcess()
	p.SetLogCallback(func(line string) {
		mu.Lock()
		logs = append(logs, line)
		mu.Unlock()
	})
	if err := p.Start(); err != nil {
		t.Fatalf("start core: %v", err)
	}
	defer p.Stop()

	deadline := time.Now().Add(15 * time.Second)
	for time.Now().Before(deadline) {
		if core.PingRpc(rpcAddr) {
			break
		}
		time.Sleep(200 * time.Millisecond)
	}
	if !core.PingRpc(rpcAddr) {
		mu.Lock()
		dump := strings.Join(logs, "\n")
		mu.Unlock()
		t.Fatalf("core RPC portal not reachable; logs:\n%s", dump)
	}
	time.Sleep(1 * time.Second)

	mu.Lock()
	joined := strings.Join(logs, "\n")
	mu.Unlock()

	// The config should be accepted and the network started.
	if !strings.Contains(joined, "adv-net") {
		t.Fatalf("core log did not show advanced network; logs:\n%s", joined)
	}
	if strings.Contains(joined, "TOML parse error") || strings.Contains(joined, "failed to parse config") {
		t.Fatalf("core reported TOML parse errors loading advanced config; logs:\n%s", joined)
	}
}
